import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import path from 'node:path';
const fixture = JSON.parse(readFileSync(process.env.QA_FIXTURE_PATH!, 'utf8'));
async function admin(page: Page) {
  await page.goto('/login');
  await page.getByLabel('用户名').fill(fixture.users.admin);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
  await page.goto('/admin/school');
}
async function upload(page: Page, noun: string, file: string) {
  await page.getByLabel(`上传${noun} Excel`).setInputFiles(fixture.roster_files[file]);
  await page.getByRole('button', { name: '上传并预校验', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入预览与结果' })).toBeVisible();
  await expect(page.getByText(`${file}.xlsx`, { exact: true }).first()).toBeVisible();
}

test('teacher Excel errors, duplicate choices, deletion and forced first-login password change', async ({ page }) => {
  await admin(page);
  await page.getByRole('button', { name: '教师档案', exact: true }).click();
  await expect(page.getByRole('button', { name: '新建教师档案', exact: true })).toHaveCount(0);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载教师资料模板（24 列）' }).click();
  expect((await download).suggestedFilename()).toBe('教师资料模板.xlsx');
  await upload(page, '教师', 'teacher-invalid');
  await expect(page.getByText('教师姓名、教师账号、状态', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '确认导入并创建账号', exact: true })).toHaveCount(0);
  await page.goto('/admin/papers');
  await page.goto('/admin/school');
  await expect(page.getByRole('button', { name: '教师档案', exact: true })).toHaveClass(/active/);
  await expect(page.getByRole('heading', { name: '导入预览与结果' })).toBeVisible();
  await expect(page.getByText('teacher-invalid.xlsx', { exact: true }).first()).toBeVisible();
  await upload(page, '教师', 'teacher-old');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const oldTeacher = page.getByRole('row').filter({ hasText: fixture.roster_accounts.old });
  await expect(oldTeacher).toContainText('131****7000');
  await oldTeacher.getByRole('button', { name: '查看档案', exact: true }).click();
  const teacherDialog = page.getByRole('dialog', { name: 'QA 流程教师 · 档案详情' });
  await expect(teacherDialog).toBeInViewport();
  await teacherDialog.getByRole('button', { name: '关闭档案', exact: true }).click();
  await expect(teacherDialog).toHaveCount(0);
  await upload(page, '教师', 'teacher-suspects');
  const confirm = page.getByRole('button', { name: '确认导入并创建账号', exact: true });
  await expect(confirm).toBeDisabled();
  await expect(page.getByLabel('第2行保留或放弃')).toHaveValue('true');
  await page.getByLabel('第3行保留或放弃').selectOption('false');
  await page.getByLabel('已核对第 2 行').check();
  await expect(confirm).toBeDisabled();
  await page.getByLabel('已核对第 3 行').check();
  await page.screenshot({ path: test.info().outputPath('teacher-duplicate-confirmation.png'), fullPage: true });
  await confirm.click();
  await expect(page.getByText(/成功 1 条 · 主动放弃 1 条/)).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const kept = page.getByRole('row').filter({ hasText: fixture.roster_accounts.keep });
  await expect(kept).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: fixture.roster_accounts.skip })).toHaveCount(0);
  await kept.getByRole('button', { name: '删除原档案', exact: true }).click();
  await page.getByRole('button', { name: '确认删除原档案', exact: true }).click();
  await expect(kept).toHaveCount(0);
  await page.getByText('教师删除记录与历史查询', { exact: true }).click();
  await page.getByLabel('删除记录姓名或账号').fill(fixture.roster_accounts.keep);
  const deleted = page.getByRole('row').filter({ hasText: fixture.roster_accounts.keep });
  await deleted.getByRole('button', { name: '查看删除快照' }).click();
  await expect(page.getByRole('region', { name: '教师删除快照' })).toContainText('QA 流程教师');
  await expect(page.getByRole('region', { name: '教师删除快照' }).locator('tbody').first().getByRole('row')).toHaveCount(24);
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.roster_accounts.old);
  await page.getByLabel('密码', { exact: true }).fill(fixture.roster_accounts.old);
  await expect(page.getByLabel('账号类型')).toHaveCount(0);
  await expect(page.getByLabel('学校 ID')).toHaveCount(0);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/change-password$/);
  await page.goto('/teacher');
  await expect(page).toHaveURL(/\/change-password$/);
  await page.getByLabel('当前密码', { exact: true }).fill(fixture.roster_accounts.old);
  await page.getByLabel('新密码（至少 8 位）', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByLabel('再次输入新密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '修改密码并进入系统' }).click();
  await expect(page).toHaveURL(/\/teacher$/);
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
});

test('teacher with teaching history can be deleted and reimported under a new login without resetting password', async ({ page, request }) => {
  await admin(page);
  await page.getByRole('button', { name: '教师档案', exact: true }).click();
  await upload(page, '教师', 'teacher-change-before');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  const login = await request.post('/api/v1/auth/login', { data: { username: fixture.roster_accounts.change, password: fixture.roster_accounts.change } });
  expect(login.ok()).toBe(true);
  const token = (await login.json()).access_token;
  const changed = await request.post('/api/v1/auth/change-password', { headers: { Authorization: `Bearer ${token}` }, data: { current_password: fixture.roster_accounts.change, new_password: process.env.QA_PASSWORD } });
  expect(changed.ok()).toBe(true);
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const teacher = page.getByRole('row').filter({ hasText: fixture.roster_accounts.change });
  await expect(teacher).toContainText('数学:10.1;');
  await teacher.getByRole('button', { name: '删除原档案', exact: true }).click();
  await page.getByRole('button', { name: '确认删除原档案', exact: true }).click();
  await expect(teacher).toHaveCount(0);
  await upload(page, '教师', 'teacher-change-after');
  await page.getByText('教师变更重导 · 对应原教师记录', { exact: true }).click();
  await page.getByLabel('查找待重导教师').fill(fixture.roster_accounts.change);
  const select = page.getByLabel('第2行原教师记录');
  await expect(select.locator('option')).toHaveCount(2);
  await select.selectOption({ index: 1 });
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByText('其中教师信息变更 1 条', { exact: true })).toBeVisible();
  await page.getByText('教师删除记录与历史查询', { exact: true }).click();
  await page.getByLabel('删除记录姓名或账号').fill(fixture.roster_accounts.change);
  await page.getByRole('button', { name: '查看删除快照', exact: true }).click();
  await expect(page.getByRole('region', { name: '教师删除快照' })).toContainText('高中一年级1班');
  await page.screenshot({ path: test.info().outputPath('teacher-reimport-history.png'), fullPage: true });
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.roster_accounts.changed);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/teacher$/);
});

test('student XLS import and login automatically identify account type', async ({ page, request }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await page.getByLabel('上传学生 Excel').setInputFiles(path.resolve(__dirname, '../../apps/api/tests/fixtures/student_roster.xls'));
  await page.getByRole('button', { name: '上传并预校验', exact: true }).click();
  await expect(page.getByText(/共 2 行 · 错误 0 行/)).toBeVisible();
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByText(/成功 2 条 · 主动放弃 0 条/)).toBeVisible();
  await upload(page, '学生', 'student-login-shared');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.users.teacher);
  await page.getByLabel('密码', { exact: true }).fill(fixture.users.teacher);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/change-password$/);
  const login = await request.post('/api/v1/auth/login', { data: { username: fixture.users.teacher, password: fixture.users.teacher } });
  expect((await login.json()).user.account_type).toBe('student');
  await page.getByLabel('当前密码', { exact: true }).fill(fixture.users.teacher);
  await page.getByLabel('新密码（至少 8 位）', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByLabel('再次输入新密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '修改密码并进入系统' }).click();
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.users.teacher);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  const identities = page.getByRole('region', { name: '确认登录身份' });
  await expect(identities.getByRole('button')).toHaveCount(2);
  await identities.getByRole('button', { name: /教师 · QA teacher/ }).click();
  await expect(page).toHaveURL(/\/teacher$/);
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByLabel('账号类型')).toHaveCount(0);
  await expect(page.getByLabel('学校 ID')).toHaveCount(0);
  await page.screenshot({ path: test.info().outputPath('automatic-login-mobile.png'), fullPage: true });
});

test('student fixed template import creates account and graduation retains the archive', async ({ page }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await expect(page.getByRole('button', { name: '新建学生档案', exact: true })).toHaveCount(0);
  await upload(page, '学生', 'student-roster');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const row = page.getByRole('row').filter({ hasText: fixture.roster_accounts.student });
  await expect(row).toContainText('已绑定账号');
  await expect(row).toContainText('高中一年级1班');
  await row.getByRole('button', { name: '毕业归档', exact: true }).click();
  await page.getByRole('button', { name: '确认毕业归档', exact: true }).click();
  await expect(row).toContainText('已毕业归档');
  await row.getByRole('button', { name: '查看档案', exact: true }).click();
  const studentDialog = page.getByRole('dialog', { name: 'QA 流程学生 · 档案详情' });
  await expect(studentDialog).toBeInViewport();
  await page.screenshot({ path: test.info().outputPath('student-graduation-archive.png'), fullPage: true });
  await page.keyboard.press('Escape');
  await expect(studentDialog).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.app-sidebar')).toBeHidden();
  await page.locator('.workspace-main').evaluate(element => { element.scrollTop = 0; });
  await expect(page.getByRole('heading', { name: '维护学生档案' })).toBeInViewport();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(overflow).toBe(false);
  await page.screenshot({ path: test.info().outputPath('student-roster-mobile.png'), fullPage: true });
});

test('student import rejects every non-normal status without writing the valid row', async ({ page }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await expect(page.getByText(/状态仅接受「正常」/)).toBeVisible();
  await upload(page, '学生', 'student-invalid-status');
  await expect(page.getByText(/共 5 行 · 错误 4 行/)).toBeVisible();
  await expect(page.getByRole('cell', { name: '状态非法', exact: true })).toHaveCount(4);
  await expect(page.getByRole('alert')).toContainText('整批未写入');
  await expect(page.getByRole('button', { name: '下载本批次错误清单', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '确认导入并创建账号', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  await page.getByLabel('学生姓名或账号').fill(fixture.roster_accounts.invalid_good);
  await expect(page.getByText('当前范围暂无记录。请调整筛选或完成数据接入。', { exact: true }).last()).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: fixture.roster_accounts.invalid_good })).toHaveCount(0);
});

test('confirmation revalidation refreshes the batch and exposes its error download', async ({ page, request }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await upload(page, '学生', 'student-confirm-race');
  const confirm = page.getByRole('button', { name: '确认导入并创建账号', exact: true });
  await expect(confirm).toBeEnabled();
  const login = await request.post('/api/v1/auth/login', { data: { username: fixture.users.admin, password: process.env.QA_PASSWORD } });
  expect(login.ok()).toBe(true);
  const headers = { Authorization: `Bearer ${(await login.json()).access_token}` };
  const base = '/api/v1/platform/education/roster';
  const uploadResponse = await request.post(`${base}/students/imports`, { headers, data: {
    filename: 'student-confirm-race.xlsx', content_base64: readFileSync(fixture.roster_files['student-confirm-race']).toString('base64'),
  } });
  expect(uploadResponse.ok()).toBe(true);
  const batch = await uploadResponse.json();
  const imported = await request.post(`${base}/imports/${batch.id}/confirm`, { headers, data: { expected_revision: batch.revision } });
  expect(imported.ok()).toBe(true);
  await confirm.click();
  await expect(page.getByText(/共 1 行 · 错误 1 行/)).toBeVisible();
  await expect(page.getByRole('cell', { name: '账号重复', exact: true })).toBeVisible();
  await expect(page.getByRole('alert')).toContainText('整批未写入');
  await expect(confirm).toHaveCount(0);
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载本批次错误清单', exact: true }).click();
  expect((await downloaded).suggestedFilename()).toBe('导入错误清单.xlsx');
});

for (const scenario of [
  { file: 'student-suspend', account: 'suspend', name: 'QA 休学学生', action: '休学', status: '已休学' },
  { file: 'student-withdraw', account: 'withdraw', name: 'QA 退学学生', action: '退学', status: '已退学' },
]) {
  test(`student ${scenario.action} stops account access and retains the archive`, async ({ page, request }) => {
    await admin(page);
    await page.getByRole('button', { name: '学生档案', exact: true }).click();
    await upload(page, '学生', scenario.file);
    await expect(page.getByText(/共 1 行 · 错误 0 行/)).toBeVisible();
    await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
    await expect(page.getByText(/成功 1 条 · 主动放弃 0 条/)).toBeVisible();
    await page.getByRole('button', { name: '关闭批次', exact: true }).click();
    const username = fixture.roster_accounts[scenario.account];
    await page.getByLabel('学生姓名或账号').fill(username);
    const row = page.getByRole('row').filter({ hasText: username });
    await expect(row).toContainText('已绑定账号');
    await expect(row).toContainText('有效');
    await expect(row).toContainText('高中一年级99班');
    await page.getByLabel('学生班级筛选').fill('98班');
    await expect(row).toHaveCount(0);
    await page.getByLabel('学生班级筛选').fill('99班');
    await expect(row).toContainText('高中一年级99班');
    const login = await request.post('/api/v1/auth/login', { data: { username, password: username } });
    expect(login.ok()).toBe(true);
    const token = (await login.json()).access_token;
    await row.getByRole('button', { name: scenario.action, exact: true }).click();
    const confirmation = page.getByRole('region', { name: '确认档案操作' });
    await expect(confirmation).toContainText('账号将立即停止访问，档案和历史成绩保留。');
    await confirmation.getByRole('button', { name: '取消', exact: true }).click();
    await expect(confirmation).toHaveCount(0);
    await expect(row).toContainText('有效');
    await row.getByRole('button', { name: scenario.action, exact: true }).click();
    await confirmation.getByRole('button', { name: `确认${scenario.action}`, exact: true }).click();
    await expect(row).toContainText(scenario.status);
    for (const action of ['休学', '退学', '毕业归档']) {
      await expect(row.getByRole('button', { name: action, exact: true })).toHaveCount(0);
    }
    await row.getByRole('button', { name: '查看档案', exact: true }).click();
    const archive = page.getByRole('dialog', { name: `${scenario.name} · 档案详情` });
    await expect(archive.locator('tbody').getByRole('row')).toHaveCount(30);
    await expect(archive.getByRole('row').filter({ has: page.getByRole('cell', { name: '状态', exact: true }) })).toContainText('正常');
    const deniedLogin = await request.post('/api/v1/auth/login', { data: { username, password: username } });
    expect([401, 403]).toContain(deniedLogin.status());
    const deniedSession = await request.get('/api/v1/auth/me', { headers: { Authorization: `Bearer ${token}` } });
    expect([401, 403]).toContain(deniedSession.status());
    await page.screenshot({ path: test.info().outputPath(`student-${scenario.account}-archive.png`), fullPage: true });
  });
}
