import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import path from 'node:path';
const fixture = JSON.parse(readFileSync(process.env.QA_FIXTURE_PATH!, 'utf8'));
async function admin(page: Page) {
  await page.goto('/login');
  await page.getByLabel('用户名').fill(fixture.users.admin);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
  await page.goto('/admin/school');
}
async function upload(page: Page, noun: string, file: string) {
  await page.getByLabel(`上传${noun} Excel`).setInputFiles(fixture.roster_files[file]);
  await page.getByRole('button', { name: '上传并预校验', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入预览与结果' })).toBeVisible();
  await expect(page.getByText(`${file}.xlsx`, { exact: true }).first()).toBeVisible();
}

test('teacher Excel errors, duplicate choices, deletion and forced first-login password change', async ({ page }) => {
  await admin(page);
  await page.getByRole('button', { name: '教师档案', exact: true }).click();
  await expect(page.getByRole('button', { name: '新建教师档案', exact: true })).toHaveCount(0);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载教师资料模板（24 列）' }).click();
  expect((await download).suggestedFilename()).toBe('教师资料模板.xlsx');
  await upload(page, '教师', 'teacher-invalid');
  await expect(page.getByText('教师姓名、教师账号、状态', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '确认导入并创建账号', exact: true })).toHaveCount(0);
  await upload(page, '教师', 'teacher-old');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: fixture.roster_accounts.old })).toContainText('131****7000');
  await upload(page, '教师', 'teacher-suspects');
  const confirm = page.getByRole('button', { name: '确认导入并创建账号', exact: true });
  await expect(confirm).toBeDisabled();
  await expect(page.getByLabel('第2行保留或放弃')).toHaveValue('true');
  await page.getByLabel('第3行保留或放弃').selectOption('false');
  await page.getByLabel('已核对第 2 行').check();
  await expect(confirm).toBeDisabled();
  await page.getByLabel('已核对第 3 行').check();
  await page.screenshot({ path: test.info().outputPath('teacher-duplicate-confirmation.png'), fullPage: true });
  await confirm.click();
  await expect(page.getByText(/成功 1 条 · 主动放弃 1 条/)).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const kept = page.getByRole('row').filter({ hasText: fixture.roster_accounts.keep });
  await expect(kept).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: fixture.roster_accounts.skip })).toHaveCount(0);
  await kept.getByRole('button', { name: '删除原档案', exact: true }).click();
  await page.getByRole('button', { name: '确认删除原档案', exact: true }).click();
  await expect(kept).toHaveCount(0);
  await page.getByText('教师删除记录与历史查询', { exact: true }).click();
  await page.getByLabel('删除记录姓名或账号').fill(fixture.roster_accounts.keep);
  const deleted = page.getByRole('row').filter({ hasText: fixture.roster_accounts.keep });
  await deleted.getByRole('button', { name: '查看删除快照' }).click();
  await expect(page.getByRole('region', { name: '教师删除快照' })).toContainText('QA 流程教师');
  await expect(page.getByRole('region', { name: '教师删除快照' }).locator('tbody').first().getByRole('row')).toHaveCount(24);
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.roster_accounts.old);
  await page.getByLabel('密码', { exact: true }).fill(fixture.roster_accounts.old);
  await expect(page.getByLabel('账号类型')).toHaveCount(0);
  await expect(page.getByLabel('学校 ID')).toHaveCount(0);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/change-password$/);
  await page.goto('/teacher');
  await expect(page).toHaveURL(/\/change-password$/);
  await page.getByLabel('当前密码', { exact: true }).fill(fixture.roster_accounts.old);
  await page.getByLabel('新密码（至少 8 位）', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByLabel('再次输入新密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '修改密码并进入系统' }).click();
  await expect(page).toHaveURL(/\/teacher$/);
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
});

test('teacher with teaching history can be deleted and reimported under a new login without resetting password', async ({ page, request }) => {
  await admin(page);
  await page.getByRole('button', { name: '教师档案', exact: true }).click();
  await upload(page, '教师', 'teacher-change-before');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  const login = await request.post('/api/v1/auth/login', { data: { username: fixture.roster_accounts.change, password: fixture.roster_accounts.change } });
  expect(login.ok()).toBe(true);
  const token = (await login.json()).access_token;
  const changed = await request.post('/api/v1/auth/change-password', { headers: { Authorization: `Bearer ${token}` }, data: { current_password: fixture.roster_accounts.change, new_password: process.env.QA_PASSWORD } });
  expect(changed.ok()).toBe(true);
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const teacher = page.getByRole('row').filter({ hasText: fixture.roster_accounts.change });
  await expect(teacher).toContainText('高中一年级1班');
  await teacher.getByRole('button', { name: '删除原档案', exact: true }).click();
  await page.getByRole('button', { name: '确认删除原档案', exact: true }).click();
  await expect(teacher).toHaveCount(0);
  await upload(page, '教师', 'teacher-change-after');
  await page.getByText('教师变更重导 · 对应原教师记录', { exact: true }).click();
  await page.getByLabel('查找待重导教师').fill(fixture.roster_accounts.change);
  const select = page.getByLabel('第2行原教师记录');
  await expect(select.locator('option')).toHaveCount(2);
  await select.selectOption({ index: 1 });
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByText('其中教师信息变更 1 条', { exact: true })).toBeVisible();
  await page.getByText('教师删除记录与历史查询', { exact: true }).click();
  await page.getByLabel('删除记录姓名或账号').fill(fixture.roster_accounts.change);
  await page.getByRole('button', { name: '查看删除快照', exact: true }).click();
  await expect(page.getByRole('region', { name: '教师删除快照' })).toContainText('高中一年级1班');
  await page.screenshot({ path: test.info().outputPath('teacher-reimport-history.png'), fullPage: true });
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.roster_accounts.changed);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/teacher$/);
});

test('student XLS import and login automatically identify account type', async ({ page, request }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await page.getByLabel('上传学生 Excel').setInputFiles(path.resolve(__dirname, '../../apps/api/tests/fixtures/student_roster.xls'));
  await page.getByRole('button', { name: '上传并预校验', exact: true }).click();
  await expect(page.getByText(/共 2 行 · 错误 0 行/)).toBeVisible();
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByText(/成功 2 条 · 主动放弃 0 条/)).toBeVisible();
  await upload(page, '学生', 'student-login-shared');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.users.teacher);
  await page.getByLabel('密码', { exact: true }).fill(fixture.users.teacher);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page).toHaveURL(/\/change-password$/);
  const login = await request.post('/api/v1/auth/login', { data: { username: fixture.users.teacher, password: fixture.users.teacher } });
  expect((await login.json()).user.account_type).toBe('student');
  await page.getByLabel('当前密码', { exact: true }).fill(fixture.users.teacher);
  await page.getByLabel('新密码（至少 8 位）', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByLabel('再次输入新密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '修改密码并进入系统' }).click();
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible();
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.getByLabel('用户名').fill(fixture.users.teacher);
  await page.getByLabel('密码', { exact: true }).fill(process.env.QA_PASSWORD!);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  const identities = page.getByRole('region', { name: '确认登录身份' });
  await expect(identities.getByRole('button')).toHaveCount(2);
  await identities.getByRole('button', { name: /教师 · QA teacher/ }).click();
  await expect(page).toHaveURL(/\/teacher$/);
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByLabel('账号类型')).toHaveCount(0);
  await expect(page.getByLabel('学校 ID')).toHaveCount(0);
  await page.screenshot({ path: test.info().outputPath('automatic-login-mobile.png'), fullPage: true });
});

test('student fixed template import creates account and graduation retains the archive', async ({ page }) => {
  await admin(page);
  await page.getByRole('button', { name: '学生档案', exact: true }).click();
  await expect(page.getByRole('button', { name: '新建学生档案', exact: true })).toHaveCount(0);
  await upload(page, '学生', 'student-roster');
  await page.getByRole('button', { name: '确认导入并创建账号', exact: true }).click();
  await expect(page.getByRole('heading', { name: '导入完成', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭批次', exact: true }).click();
  const row = page.getByRole('row').filter({ hasText: fixture.roster_accounts.student });
  await expect(row).toContainText('已绑定账号');
  await expect(row).toContainText('高中一年级1班');
  await row.getByRole('button', { name: '毕业归档', exact: true }).click();
  await page.getByRole('button', { name: '确认毕业归档', exact: true }).click();
  await expect(row).toContainText('已毕业归档');
  await row.getByRole('button', { name: '查看档案', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'QA 流程学生 · 档案详情' })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('student-graduation-archive.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.app-sidebar')).toBeHidden();
  await page.locator('.workspace-main').evaluate(element => { element.scrollTop = 0; });
  await expect(page.getByRole('heading', { name: '维护学生档案' })).toBeInViewport();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  expect(overflow).toBe(false);
  await page.screenshot({ path: test.info().outputPath('student-roster-mobile.png'), fullPage: true });
});
