s=section('analysis','班级分析','教师从选择班级开始，判断资料是否齐备，再查看表现、定位问题与教学跟进。','让分析结果能支持下一步教学行动；资料缺失或有误时交回对应负责人处理。')
f=flow(s,'class-review','查看班级表现并决定下一步','教师准备考试讲评，或学校需要了解班级整体表现',['教师 / 学校管理者','系统','教务 / 成绩负责人'],['班级名单与任教安排','考试科目及满分','该班学科成绩','小题丢分与已确认知识点'],['班级表现概览','需要进一步查看的学生或问题','人工确定的教学跟进事项'],['教师只能查看当前有效任教班级及学科。学校管理员查看本校范围。','班级统计按当前班级归属计算；知识点多标签可能重复计入，不能将各标签丢分直接相加当作总丢分。'])
node(f,'s',0,0,'准备开展考后教学分析','start');node(f,'select',0,1,'选择班级、学科和考试',module='班级分析')
node(f,'scope',1,1,'属于当前可查看范围？','decision');node(f,'access',2,2,'核对教师任教与班级安排','subprocess',target='teaching-change',detail='由教务核查实际任教安排；没有对应教学职责时不扩大查看范围。')
node(f,'read',1,3,'检查该范围成绩是否齐备');node(f,'data',1,4,'已有可用于分析的成绩？','decision')
node(f,'missing',2,5,'补充或核实成绩资料','subprocess',target='upload-check',detail='系统无成绩时显示暂无；教务需确认是否未导入、选错考试或学生归属有误。')
node(f,'show',1,6,'展示人数、均分、分布与丢分情况',outputs=['有成绩的学生人数','平均分、最高分、最低分','得分率分布','可用的知识点丢分统计'])
node(f,'review',0,6,'结合样本与考试口径解读结果',detail='人数是有成绩的样本数。比较两次考试时先看满分和样本是否可比；缺少比较条件时不强行推断进退步。',mode='manual')
node(f,'next',0,7,'需要核查什么？','decision',mode='manual');node(f,'individual',0,8,'进入学生详情核查个体问题','subprocess',module='学生学情',target='student-review')
node(f,'error',2,8,'核实分数或名单疑点','subprocess',target='score-correction');node(f,'teach',0,9,'安排讲评、辅导或线下沟通',mode='manual',detail='教学安排是教师的业务动作；当前页面没有自动下发教学计划的功能。')
node(f,'end',0,10,'本轮班级分析与跟进安排完成','end')
path(f,'s','select','scope');edge(f,'scope','access','否','return');edge(f,'access','select','核实后重新选择','return');edge(f,'scope','read','是');path(f,'read','data');edge(f,'data','missing','否','return');edge(f,'missing','select','补齐后重新查看','return');edge(f,'data','show','是');path(f,'show','review','next');edge(f,'next','individual','个体学情');edge(f,'next','error','数据疑点');edge(f,'next','teach','可直接教学跟进');path(f,'individual','teach');edge(f,'error','select','核实后重看','return');path(f,'teach','end')
s['notes']=[['这里的增删改在哪里','班级分析是查看与分析环节。需改分就回成绩导入，需改名单就回教务，需补知识点就回题目资料维护；不是直接编辑分析结论。']]

s=section('learning','学生学情','由教师或学校管理者查看特定学生，核对成绩、小题和需要跟进的问题。','把“查看学生”继续展开到“判断问题、核实资料、采取行动”。')
f=flow(s,'student-review','查看学生 → 判断问题 → 分流处理','从班级分析下钻，或在学生名单中选择要关注的学生',['教师 / 学校管理者','系统','教务 / 成绩负责人','学生'],['授权范围内的学生名单','个人历次学科成绩','个人小题丢分','已有待跟进标记'],['本次学情核查结果','教学沟通事项或资料更正任务'],['教师只见任教学科；不能因为能够打开学生详情就查看其全部学科总分。','已有风险标记用于提醒跟进，不表示系统已从分数自动得出最终结论。'])
node(f,'s',0,0,'确定需要关注的学生','start');node(f,'search',0,1,'搜索姓名、学号或筛选待跟进',module='学生学情')
node(f,'scope',1,1,'学生在可查看范围内？','decision');node(f,'fixscope',2,2,'核对学生归属和任教安排',mode='manual',detail='如果不是当前应服务的学生，停止查看；如果档案或任教有误，由教务在对应维护页处理。')
node(f,'closed',2,3,'无法授权时结束本次查看','end')
node(f,'show',1,3,'展示授权成绩历史与小题丢分',outputs=['历次学科成绩','本人小题丢分记录','管理角色可读的总分'])
node(f,'compare',0,4,'结合考试和分数核对学情',mode='manual');node(f,'problem',0,5,'是否发现资料错误或缺失？','decision',mode='manual')
node(f,'correct',2,6,'核对并更正名单或成绩','subprocess',target='score-correction',detail='班级或身份问题回教务；成绩问题回成绩负责人核查，再通过导入更正。')
node(f,'plan',0,6,'确定需要讲解或跟进的内容',mode='manual');node(f,'talk',3,7,'与老师核对疑问和学习安排',mode='manual',detail='此处是教学沟通，非系统自动消息推送。学生也可以主动在智能问答中查看本人分数依据。')
node(f,'ask',3,8,'需要时进入本人智能问答','subprocess',module='智能问答',target='ask-answer')
node(f,'end',0,9,'本次学情核查与跟进完成','end')
path(f,'s','search','scope');edge(f,'scope','fixscope','否');edge(f,'fixscope','search','更正后重新查询','return');edge(f,'fixscope','closed','确无查看职责');edge(f,'scope','show','是');path(f,'show','compare','problem');edge(f,'problem','correct','是');edge(f,'correct','search','核实后再查','return');edge(f,'problem','plan','否');path(f,'plan','talk');edge(f,'talk','ask','需要自助核对时','optional');path(f,'ask','end');edge(f,'talk','end','沟通已完成')

f=flow(s,'student-practice','学生查看错题并记录订正','学生希望了解某道题的失分并进行复习',['学生','系统','学校资料负责人'],['本人小题得分','已确认的题目正文、答案与解析'],['本人订正笔记','学生自评掌握状态','可选下次复习时间'],['复习记录为学生主动填写；当前不自动批改、不自动推断掌握，也不自动作为问答记忆。'])
node(f,'s',0,0,'选择一道需要复盘的小题','start');node(f,'read',1,1,'核对本人得分和原题资料');node(f,'source',1,2,'已有确认过的原题？','decision')
node(f,'lack',0,3,'查看得分并联系学校补原题');node(f,'fill',2,4,'人工核对并补充题目来源',mode='manual',module='试卷 / 题库',detail='这是相邻的试卷与题库业务；需绑定明确的正式原题，不能凭同题号猜测。')
node(f,'show',1,5,'展示原题、参考答案与解析');node(f,'add',0,5,'加入复盘并填写订正',inputs=['订正笔记','自评掌握程度','可选复习时间'])
node(f,'save',1,6,'保存本次订正并保留历史');node(f,'end',0,7,'回看订正并继续复习','end')
path(f,'s','read','source');edge(f,'source','lack','否');path(f,'lack','fill');edge(f,'fill','read','补齐后重新查看','return');edge(f,'source','show','是');path(f,'show','add','save','end')
