s=section('chat','学生智能问答','从学生提出一个真实疑问，到系统查证本人资料、回答、核对依据与继续追问。','回答必须能落到本人可用资料；资料不足、报告无权阅读和回答失败都要有明确去向。')
f=flow(s,'ask-answer','学生提问 → 资料核对 → 回答 → 确认解决','学生想了解某次考试表现、成绩变化、小题失分或正式报告',['学生','系统','学校服务人员'],['本人账号与档案','本人已导入成绩','可选考试与学科','学生问题','需要诊断时的正式报告及授权'],['回答及对应依据','或资料缺失、权限限制与重试提示'],['成绩问答可以在成绩可用后独立开展，不需要教师先完成班级分析。','没有数据、没有正式报告或没有报告权限时，不把猜测作为正式事实。当前回答检查仍是有限规则，学生可主动核对和反馈。'])
node(f,'s',0,0,'产生一个学习或成绩疑问','start');node(f,'login',0,1,'登录并进入智能问答',module='智能问答')
node(f,'identity',1,1,'能够确认本人身份？','decision',rule='账号有效，具有学生身份，且已绑定有效的本人档案。')
node(f,'contact',2,2,'协助核对账号与学生档案','subprocess',target='student-onboard');node(f,'wait',0,2,'暂不具备条件时结束本次问答','end')
node(f,'ask',0,3,'选择考试、学科并输入问题',inputs=['考试与学科选择','问题正文'],detail='发送过程中先等待回答完成再切换范围；需要比较时尽量明确考试名称和科目。')
node(f,'kind',1,4,'判断本次要查询的内容',detail='对应考试概况、学科成绩、前后变化、历次趋势、小题丢分或正式报告；当前单轮通常只处理一个主要数据查询。')
node(f,'data',1,5,'所需资料可用且允许读取？','decision',rule='成绩为本人；正式报告还要匹配有效授权；当前范围缺记录时如实提示。')
node(f,'lack',1,6,'说明资料或权限限制',outputs=['缺少何种资料或当前不可读的说明'])
node(f,'fix',0,7,'调整问题或联系学校补资料',detail='选错范围可重新选择；缺成绩由学校核查导入；缺报告或授权按报告业务办理。',mode='manual')
node(f,'answer',1,8,'用已查到的资料整理回答')
node(f,'safe',1,9,'出现必须阻止展示的问题？','decision',rule='对疑似编造分数、涉及其他学生信息等命中规则的内容阻止直接展示；一般提示项不一定阻止回答。')
node(f,'stop',1,10,'改为提示联系老师核实')
node(f,'show',1,11,'展示回答与可核对的依据',outputs=['回答正文','本次回答所用成绩或报告依据'])
node(f,'read',0,11,'阅读回答并核对考试与分数');node(f,'done',0,12,'疑问已经解决？','decision')
node(f,'end',0,13,'完成本次问答','end');node(f,'help',2,13,'按反馈或人工流程处理','subprocess',target='human-service')
path(f,'s','login','identity');edge(f,'identity','contact','否');edge(f,'contact','login','已修复后重试','return');edge(f,'contact','wait','当前未解决');edge(f,'identity','ask','是');path(f,'ask','kind','data');edge(f,'data','lack','否');path(f,'lack','fix');edge(f,'fix','ask','条件具备后重新提问','return');edge(f,'fix','wait','暂时无法补齐');edge(f,'data','answer','是');path(f,'answer','safe');edge(f,'safe','stop','是');edge(f,'safe','show','否');edge(f,'stop','help','学生主动寻求帮助','optional');edge(f,'stop','end','本次停止');path(f,'show','read','done');edge(f,'done','end','是');edge(f,'done','ask','继续追问','return');edge(f,'done','help','需要人工核对');edge(f,'help','done','学生复核处理结果','return')

f=flow(s,'answer-evidence','查看回答依据 / 切换范围 / 重试 / 结束会话','学生已经有一个会话，需要进一步核对或调整',['学生','系统','学校服务人员'],['已有问答记录','所选考试与学科','本次回答的依据'],['可核对的历史依据','新的问题或处理结果','结束使用的会话'],['历史回答保存当时引用的资料；成绩更正不会自动改写旧答案。重新提问才能获得新查询结果。'])
node(f,'s',0,0,'需要继续处理已有会话','start');node(f,'choice',0,1,'现在想做什么？','decision')
node(f,'source',1,2,'检查该条依据是否仍可查看',detail='打开依据重新核对本人范围；报告依据再次核对当前阅读权限。')
node(f,'allow',1,3,'仍具备查看条件？','decision');node(f,'view',0,4,'查看回答时使用的资料');node(f,'denied',2,4,'协助解释缺资料或权限变化',mode='manual')
node(f,'scope',0,5,'待当前回答结束后修改范围',detail='选择已有本人数据的考试与学科，随后提交新问题。')
node(f,'retry',1,6,'重试失败请求或回读已完成回答',detail='中断后可以重试；已经完成的同一请求复用原回答，避免重复创建。')
node(f,'archive',1,7,'归档会话并保留已有记录',detail='归档后不再从该会话继续提问；当前没有恢复和逐条修改旧消息的入口。')
node(f,'end',0,8,'核对完成或开始下一次提问','end')
path(f,'s','choice');edge(f,'choice','source','查看依据');edge(f,'choice','scope','换考试或学科');edge(f,'choice','retry','回答失败重试');edge(f,'choice','archive','结束该会话');path(f,'source','allow');edge(f,'allow','view','是');edge(f,'allow','denied','否');path(f,'view','end');path(f,'denied','end');path(f,'scope','end');path(f,'retry','end');path(f,'archive','end')
s['notes']=[['与五个模块如何衔接','教务确定本人身份和考试范围；成绩导入提供分数；正式报告提供已授权解释依据；班级分析和学生学情帮助老师核实问题。'],['哪些不属于当前业务','教师看过班级分析，不会自动生成学生诊断报告；学生提问也不会自动改成绩、改班级、删报告或向教师创建处理任务。']]

s=section('service','反馈与人工处理','把“回答未解决”接到明确的工作人员、资料责任人和学生复核。','问题有人接、资料有人核、结果可查看，未解决可以继续处理。')
f=flow(s,'human-service','提出疑问 → 接单核查 → 回复 → 确认或重开','学生需要人工帮助，或对回答及其依据有疑问',['学生','系统','受理人员 / 教师','相关资料负责人'],['具体问题与补充说明','相关考试或回答','必要的成绩或报告核对材料'],['人工回复和处理说明','已解决并确认的工单，或重新打开的工单'],['人工工单由学生主动发起；系统的回答检查不会自动替学生创建工单。','内部转给资料负责人核实属于人工协作，不表示已经实现系统自动派单或跨模块审批。'])
node(f,'s',0,0,'认为需要人工核实','start');node(f,'submit',0,1,'提交人工请求并说明问题',module='人工支持',inputs=['问题原因','情况描述','可选关联会话'])
node(f,'queue',1,1,'保存请求并放入待处理队列');node(f,'accept',2,2,'查看授权范围内请求并接单')
node(f,'check',2,3,'核实问题并与学生补充沟通');node(f,'correct',2,4,'是否需要资料负责人处理？','decision',mode='manual')
node(f,'owner',3,5,'核对成绩、档案或正式报告',mode='manual',detail='成绩更正走新批次导入；班级或账号问题回教务；正式报告更正使用新版本。')
node(f,'donefix',3,6,'反馈已核实的资料与处理结果',mode='manual')
node(f,'reply',2,7,'回复学生并填写实际处理说明');node(f,'save',1,7,'记录消息与已解决状态')
node(f,'read',0,8,'查看回复并核对结果');node(f,'ok',0,9,'问题已解决？','decision')
node(f,'close',1,10,'记录学生确认并关闭');node(f,'reopen',0,10,'填写仍未解决的原因并重开')
node(f,'back',1,11,'恢复待处理，等待重新接单');node(f,'end',0,12,'本次人工服务完成','end')
path(f,'s','submit','queue','accept','check','correct');edge(f,'correct','owner','是');path(f,'owner','donefix','reply');edge(f,'correct','reply','否：可直接解释');path(f,'reply','save','read','ok');edge(f,'ok','close','是');edge(f,'ok','reopen','否','return');path(f,'reopen','back');edge(f,'back','accept','再次受理','return');path(f,'close','end')

f=flow(s,'answer-feedback','对回答评价 → 学校核查 → 回看处理结果','学生认为回答有帮助、无帮助、数据有误或表达不当',['学生','系统','反馈处理人员','相关资料负责人'],['被评价的回答','评价类别','可选补充说明'],['回答评价记录','学校处理结论'],['反馈处理不会自动修改成绩或训练模型；必要的资料更正要回到对应生产环节。'])
node(f,'s',0,0,'决定评价一条回答','start');node(f,'submit',0,1,'选择评价并补充具体说明',module='智能问答 / 反馈')
node(f,'save',1,1,'保存评价并进入处理队列');node(f,'review',2,2,'查看反馈并定位具体问题');node(f,'type',2,3,'需要核查原始资料？','decision',mode='manual')
node(f,'owner',3,4,'与原资料核对并按需更正',mode='manual',detail='成绩、账号、班级或报告分别交对应负责人处理。')
node(f,'resolve',2,5,'填写实际处理结果并更新状态');node(f,'read',0,6,'在支持入口回看处理状态');node(f,'more',0,7,'仍需要进一步帮助？','decision')
node(f,'service',0,8,'主动提交人工帮助请求','subprocess',target='human-service');node(f,'end',0,9,'本条反馈处理完成','end')
path(f,'s','submit','save','review','type');edge(f,'type','owner','是');path(f,'owner','resolve');edge(f,'type','resolve','否');path(f,'resolve','read','more');edge(f,'more','service','是');edge(f,'more','end','否');path(f,'service','end')
