s=section('overview','全业务总流程','以一次考试为起点，看清学校、系统、教师和学生之间的工作交接。','让业务负责人能顺着箭头说明：工作怎样开始，由谁处理，何时完成，出错交给谁。')
f=flow(s,'exam-to-service','一次考试如何走到教学分析与学生答疑','学校安排考试并准备为师生提供考后服务',['教务 / 数据负责人','系统','教师','学生'],['师生与班级名单','任教安排','考试与科目安排','学校确认的成绩资料'],['教师可查看授权学情','学生可基于本人资料提问','疑问得到答复或进入人工处理'],['成绩保存成功后，教师分析与学生问答可分别开展，不要求先完成教师分析。','正式报告是可选的补充材料，由学校提交；系统不会根据班级分析自动生成正式报告。'])
node(f,'start',0,0,'安排一次考试','start')
node(f,'roster',0,1,'核对师生、班级与考试安排','subprocess',module='师生班级与考试',target='exam-setup',inputs=['学生名单','教师任教安排','考试名称、日期、科目及满分'],outputs=['可使用的师生档案与考试安排'])
node(f,'upload',0,2,'准备并提交成绩资料','subprocess',module='成绩导入',target='upload-check',inputs=['考试总分表','学科成绩表','小题得分表'])
node(f,'check',1,2,'成绩检查通过？','decision',detail='检查学生和考试是否对应、各科满分是否一致、得分和丢分是否合理。')
node(f,'fix',0,3,'按问题清单修正后重交',detail='资料内容有误时由成绩负责人修正；列对应关系错误时可调整对应关系。',inputs=['导入问题清单'],mode='manual')
node(f,'save',1,4,'保存成绩并反馈导入结果',outputs=['成绩导入结果','可查询的本次考试成绩'])
node(f,'split',1,5,'分别开展考后服务','fork',detail='以下是可独立开展的业务，不表示系统自动向师生发送通知。')
node(f,'teach',2,6,'查看班级与个体学情','subprocess',module='班级分析 / 学生学情',target='class-review')
node(f,'act',2,7,'核对重点问题并安排教学跟进',detail='教师结合班级分布和个体学情决定讲评、辅导或线下沟通。当前没有自动生成或下发教学任务。',mode='manual')
node(f,'teachend',2,8,'本轮教学分析完成','end')
node(f,'report',0,6,'有正式报告时提交原件','subprocess',module='正式报告原件',target='report-register',inputs=['学校确认的正式报告原件与摘要'])
node(f,'record',1,7,'保存报告并按现有授权开放',detail='报告资料成为后续读取的依据；上传报告不自动开通阅读授权。')
node(f,'reportend',1,8,'报告资料准备完成','end')
node(f,'ask',3,6,'选择考试并提出疑问','subprocess',module='智能问答',target='ask-answer',inputs=['本人已导入的成绩','学生问题'])
node(f,'answer',3,8,'阅读回答并核对依据',detail='基础成绩可以直接用于本人问答；涉及正式报告时需该报告的有效阅读授权。')
node(f,'resolved',3,9,'疑问已解决？','decision')
node(f,'end',3,10,'完成本次学习核对','end')
node(f,'help',2,10,'进入反馈或人工处理','subprocess',module='反馈 / 人工支持',target='human-service',detail='学生主动提交反馈或人工请求，工作人员在授权范围内核查。')
node(f,'reply',2,11,'反馈处理结果并由学生复核',detail='学生查看处理结果；若资料被更正，可重新选择考试发起提问。',mode='manual')
path(f,'start','roster','upload','check')
edge(f,'check','save','通过');edge(f,'check','fix','不通过','return');edge(f,'fix','upload','修正后重交','return')
path(f,'save','split');edge(f,'split','teach','教师分析');edge(f,'split','ask','学生答疑');edge(f,'split','report','有正式报告时','optional')
path(f,'teach','act','teachend');path(f,'report','record','reportend');path(f,'ask','answer','resolved')
edge(f,'resolved','end','是');edge(f,'resolved','help','否');path(f,'help','reply');edge(f,'reply','resolved','学生再次确认','return')
s['notes']=[['如何读这张图','同一列是同一责任方；箭头表示工作移交或下一步；菱形上的问题决定去向；虚线活动表示需人工完成或有条件开展。'],['图上的“资料”是什么','使用学生名单、考试安排、成绩表、正式报告、问题清单等业务名称。点击步骤即可查看所需资料、处理规则、产出和关联模块。']]
