s=section('reports','正式报告原件','学校提交已经确认的正式材料；系统保存版本，学生在阅读权限内查看与引用。','把“上传报告”和“学生有权读报告”两项业务条件分开，明确缺件、退回与更新版本的处理。')
f=flow(s,'report-register','收取正式报告 → 核对归属 → 保存版本','学校已经取得或完成一份正式报告，准备提供给学生',['报告负责人','教务管理员','系统'],['正式诊断报告、成绩报告或批阅文件原件','学生与考试信息','报告类型、版本、生成时间','正式摘要与可选报告原文'],['已核对的正式报告版本','与该版本配套的原件'],['报告的撰写或审核由学校已有工作流程完成；本模块不自动从成绩生成正式报告，也不自动批阅。'])
node(f,'s',0,0,'学校确认正式报告内容','start',mode='manual');node(f,'handover',0,1,'交付原件、摘要和归属信息',mode='manual',outputs=['正式报告资料包'])
node(f,'upload',1,1,'上传正式报告原件',module='正式报告原件');node(f,'file',2,2,'文件有效且符合要求？','decision',rule='支持PDF、PNG、JPEG；单份不超过15MB、100页。')
node(f,'replace',0,3,'提供可读取的正确原件',mode='manual');node(f,'link',1,3,'选择学生、考试并填写版本',inputs=['学生','考试','可选学科','报告类型','版本号','生成时间','正式摘要'])
node(f,'correct',1,4,'核对原件与所选学生是否一致',mode='manual',detail='系统检查范围和重复，无法代替学校核实文件正文是否属于该学生。')
node(f,'valid',2,4,'归属、版本和原件用途允许？','decision',rule='相关对象须在本校；同学生、考试、学科、类型的相同版本不能重复创建；报告原件不能同时用作其他报告或试卷。')
node(f,'fix',1,5,'修正归属、版本或重新上传');node(f,'save',2,6,'保存正式报告及其固定原件')
node(f,'read',1,6,'查看报告清单并打开原件核对');node(f,'end',1,7,'正式报告资料准备完成','end',rule='这一步不自动授予学生阅读权限；学生能否阅读进入下一流程。',target='report-read')
path(f,'s','handover','upload','file');edge(f,'file','replace','否','return');edge(f,'replace','upload','更换文件后重传','return');edge(f,'file','link','是');path(f,'link','correct','valid');edge(f,'valid','fix','否','return');edge(f,'fix','upload','需换原件时','return');edge(f,'fix','link','只改归属或版本','return');edge(f,'valid','save','是');path(f,'save','read','end')

f=flow(s,'report-read','学生查看报告 / 在问答中使用报告','学生打开正式报告，或提出需要正式诊断依据的问题',['学生','系统','学校服务负责人'],['本人已发布的正式报告','该报告的当前有效阅读授权'],['本人可读的报告内容或原件','或缺报告、缺原件、缺授权的具体提示'],['学生只读本人且在授权范围内的正式报告。上传成功不代表自动开通阅读权限。','问答使用学校提供的结构化报告内容；不会自动阅读整个PDF并重新诊断。'])
node(f,'s',0,0,'打开报告或提出诊断疑问','start');node(f,'auth',1,1,'具有当前报告阅读权限？','decision',rule='授权应有效且未到期，并覆盖该学生及相应考试、学科或报告。')
node(f,'contact',0,2,'按提示联系学校核对权限');node(f,'service',2,3,'按学校现有流程核对权益',mode='manual',detail='当前报告管理页没有开通或撤销权益的完整办理入口；不能把此动作误认为页面内的自动开通。')
node(f,'endwait',0,4,'暂无权限时结束本次读取','end')
node(f,'exists',1,3,'该范围有正式报告？','decision');node(f,'missing',2,4,'核查报告是否尚未提供',mode='manual',detail='无正式报告时不得把普通建议当成正式报告；需要时由报告负责人走正式提交流程。')
node(f,'endmissing',0,5,'待学校补充正式材料','end')
node(f,'type',0,6,'需要如何使用？','decision');node(f,'view',1,7,'展示可用报告与原件',detail='原文与附件分别检查；有摘要不代表一定有原文或原件。缺少时明确提示，不用摘要冒充原件。')
node(f,'answer',1,8,'基于可读报告整理问答解释',rule='当前具体科目与报告类型的匹配仍需核对；不宣称所有诊断问题都能自动准确选中指定学科报告。')
node(f,'check',0,9,'核对报告名称、时间与版本');node(f,'end',0,10,'完成报告阅读或解读','end')
path(f,'s','auth');edge(f,'auth','contact','否');path(f,'contact','service');edge(f,'service','auth','条件具备后重试','return');edge(f,'service','endwait','当前仍不可读');edge(f,'auth','exists','是');edge(f,'exists','missing','否');path(f,'missing','endmissing');edge(f,'exists','type','是');edge(f,'type','view','看原报告');edge(f,'type','answer','需要问答解释');path(f,'view','check');path(f,'answer','check','end')

f=flow(s,'report-correct','报告内容有误 → 核实 → 提交新版本','学生、教师或学校发现正式报告内容或附件有误',['发现问题的人','报告负责人','教务管理员','系统'],['有疑问的报告及其版本','具体错误说明','学校确认的修订材料'],['保留旧版的新正式报告','核实后的处理说明'],['当前不提供覆盖旧报告内容、直接替换旧附件或删除报告的操作；纠错采用新版本。','新增报告版本后仍需核查新版本是否在学生的阅读授权内。'])
node(f,'s',0,0,'指出报告问题和具体版本','start');node(f,'verify',1,1,'对照原报告核实疑问',mode='manual');node(f,'wrong',1,2,'确需更正报告？','decision',mode='manual')
node(f,'explain',1,3,'说明原报告依据与适用范围',mode='manual');node(f,'new',1,4,'确认修订内容并提供新原件',mode='manual')
node(f,'record',2,4,'按新版本提交正式报告','subprocess',target='report-register');node(f,'keep',3,5,'保存新版本并保留原有版本')
node(f,'tell',1,6,'告知处理结论与版本变化',mode='manual');node(f,'read',0,6,'在授权范围内重新核对');node(f,'end',0,7,'本次报告问题处理完成','end')
path(f,'s','verify','wrong');edge(f,'wrong','explain','否');edge(f,'wrong','new','是');path(f,'new','record','keep','tell');path(f,'explain','tell','read','end')
