s=section('school','师生班级与考试','把新建、修改、停用、绑定与任教调整画成具体业务场景。','先把“谁属于哪个班、谁教哪一科、参加哪次考试”核对清楚，再进入成绩和问答服务。')
f=flow(s,'class-maintain','新增班级 / 修改班级名称','新增教学班，或现有班级需要更名',['教务管理员','系统'],['班级名称','学校确认的班级标识'],['可使用的班级名单'],['外部导入的班级资料由原资料来源维护，不能直接在原生编辑入口更名。'])
node(f,'s',0,0,'收到建班或更名需求','start');node(f,'select',0,1,'新建班级或选中待改班级',module='师生班级与考试')
node(f,'edit',0,2,'填写并核对班级信息',inputs=['班级名称','新建时的班级标识'],outputs=['待保存的班级资料'])
node(f,'check',1,2,'资料允许保存？','decision',rule='名称和标识完整；班级标识不能重复；已有班级须允许本校编辑。')
node(f,'fix',0,3,'按提示修正资料',detail='名称或标识有误时修正后重交。外部来源资料需回原来源更正。',mode='manual')
node(f,'save',1,4,'保存班级并展示最新名单',outputs=['班级名称','有效状态'])
node(f,'confirm',0,4,'核对保存结果');node(f,'end',0,5,'班级可用于分班与任教','end')
path(f,'s','select','edit','check');edge(f,'check','save','是');edge(f,'check','fix','否','return');edge(f,'fix','edit','修正后再提交','return');path(f,'save','confirm','end')

f=flow(s,'student-onboard','新增学生并绑定登录账号','新生入校或补建学生档案',['教务管理员','系统','学生'],['学生姓名、学号、学校确认的学生标识','有效班级名单','已有学生登录账号'],['学生档案','账号与本人档案的绑定结果'],['导入或新建学生档案不会自动开通登录账号；账号开通沿用学校已有身份办理流程。'])
node(f,'s',0,0,'收到新生或补档需求','start');node(f,'fill',0,1,'填写学生资料并选择班级',module='师生班级与考试',inputs=['姓名','学号','学生标识','班级'])
node(f,'valid',1,1,'身份和班级正确？','decision',rule='同校、班级有效；学生标识和学号不能与另一学生冲突。')
node(f,'fix',0,2,'核对名单并改正错误',mode='manual');node(f,'save',1,3,'保存学生档案',outputs=['学生档案','当前班级'])
node(f,'account',0,3,'已有可用学生账号？','decision')
node(f,'open',0,4,'按学校流程办理账号',mode='manual',detail='属于已有身份管理工作；本页没有自动开户或默认密码发放功能。')
node(f,'bind',0,5,'选择本人账号并确认绑定',inputs=['学生档案','本校有效学生账号'])
node(f,'unique',1,5,'账号确属该学生且无冲突？','decision',rule='账号必须为本校有效学生账号，且未被其他学生档案使用；不直接覆盖已有不同绑定。')
node(f,'review',0,6,'核查账号归属并重新选择',mode='manual',detail='有占用或错绑时先走学校身份核查；当前没有直接解绑换绑入口。')
node(f,'ready',1,7,'保存绑定并提示结果',outputs=['账号绑定结果'])
node(f,'login',2,7,'登录并核对本人身份');node(f,'end',2,8,'本人学习服务入口可用','end',rule='能否看到成绩仍取决于该学生是否已有成绩；正式报告还需阅读授权。')
path(f,'s','fill','valid');edge(f,'valid','fix','否','return');edge(f,'fix','fill','修正后重交','return');edge(f,'valid','save','是');path(f,'save','account');edge(f,'account','bind','是');edge(f,'account','open','否');path(f,'open','bind','unique');edge(f,'unique','review','否','return');edge(f,'review','bind','核实后再绑定','return');edge(f,'unique','ready','是');path(f,'ready','login','end')

f=flow(s,'student-change','学生转班 / 停用学生档案','学生转班、离校，或学校决定停止该档案的使用',['教务管理员','系统','相关教师 / 学生'],['已核实的学生名单','调整后的班级安排或停用决定'],['新的班级归属或停用状态','保留的历史成绩与报告'],['当前学生维护页可改班级与状态，不能在此直接改姓名或学号；来源资料更正走原来源。'])
node(f,'s',0,0,'确认转班或停用事项','start',mode='manual');node(f,'select',0,1,'选择学生并核对本人身份',module='师生班级与考试')
node(f,'choose',0,2,'本次处理什么？','decision');node(f,'class',0,3,'选择新班级并保留有效状态');node(f,'inactive',2,3,'确认学校要求停止该档案',mode='manual',detail='业务责任人确认后由教务操作；此节点不表示产品中存在审批按钮。')
node(f,'submit',0,4,'提交班级或停用调整');node(f,'check',1,4,'资料允许调整？','decision',rule='须为本校允许编辑的档案；转入班级有效。')
node(f,'correct',0,5,'按提示核实来源或班级',mode='manual');node(f,'save',1,6,'保存调整并保留历史资料')
node(f,'read',2,6,'重新查看当前可用范围',detail='转班影响教师查询和当前班级统计；档案停用后不能继续使用该学生身份问答。历史资料仍保留。')
node(f,'end',0,7,'核对调整结果完成','end')
path(f,'s','select','choose');edge(f,'choose','class','转班');edge(f,'choose','inactive','停用');path(f,'class','submit');path(f,'inactive','submit','check');edge(f,'check','correct','否','return');edge(f,'correct','submit','核实后重交','return');edge(f,'check','save','是');path(f,'save','read','end')

f=flow(s,'teaching-change','维护教师账号与安排任教','教师显示名称变化、账号停用，或班级学科任教安排调整',['教务管理员','系统','教师'],['本校已有教师账号','班级名单','学科清单','任教生效和结束时间'],['教师账号维护结果','有效任教安排'],['新教师账号的开通走已有身份流程；任教设置按班级与学科确定范围。'])
node(f,'s',0,0,'收到教师或任教调整需求','start');node(f,'type',0,1,'维护哪类事项？','decision')
node(f,'user',0,2,'修改教师显示名称或账号状态',module='师生班级与考试',inputs=['已有教师账号','新的显示名称或使用状态'])
node(f,'assign',2,2,'确认所教班级、学科和时间',mode='manual',detail='由教务与教师确认实际任教安排；不是新增系统审批环节。')
node(f,'grant',0,3,'新增或修改任教安排',inputs=['教师账号','班级','学科','生效时间','到期时间','有效或停用状态'])
node(f,'check',1,3,'账号与任教安排有效？','decision',rule='任教必须对应本校有效教师；启用任教时班级有效；结束时间晚于生效时间。账号维护则核验本校教师归属。')
node(f,'fix',0,4,'纠正账号选择或任教信息',mode='manual');node(f,'save',1,5,'保存账号状态或任教安排')
node(f,'read',2,5,'重新登录或查看任教范围',detail='账号停用后不可登录；任教停止或到期后，不再开放对应班级学科查询。')
node(f,'end',0,6,'教师可用范围核对完成','end')
path(f,'s','type');edge(f,'type','user','账号维护');edge(f,'type','assign','任教安排');path(f,'assign','grant','check');edge(f,'user','check','提交账号修改');edge(f,'check','fix','否','return');edge(f,'fix','type','重新选择事项','return');edge(f,'check','save','是');path(f,'save','read','end')

f=flow(s,'exam-setup','建立考试 / 修改考试安排与满分','学校确定一场考试，或需要修订考试安排',['教务管理员','系统','成绩负责人'],['学科清单','考试名称、类型与日期','各科满分'],['可用于成绩整理的考试与科目安排'],['停用考试保留历史资料；当前不能把“停用”理解为所有查询立即隐藏该考试。'])
node(f,'s',0,0,'确认考试安排','start',mode='manual');node(f,'subject',0,1,'核对学科，缺少时先新增',module='师生班级与考试',inputs=['学科名称','学科代码','学校确认的学科标识'])
node(f,'exam',0,2,'新建考试或修改考试信息',inputs=['考试名称','类型','开始与结束日期','学校确认的考试标识'])
node(f,'date',1,2,'考试资料完整有效？','decision');node(f,'fix',0,3,'修正名称、日期或标识');node(f,'save',1,4,'保存考试安排')
node(f,'full',0,4,'配置考试科目与满分',inputs=['考试科目','各科满分'])
node(f,'used',1,5,'改满分会影响已有成绩？','decision',rule='已有该考试科目的成绩时，不允许在此直接改变该科历史满分。新增或保持原满分可继续。')
node(f,'resolve',2,6,'核对历史口径，暂不改满分',mode='manual',detail='需由成绩负责人核查历史材料后确定处理方式；本步骤不表示系统已有跨批次自动更正或统一换算功能。')
node(f,'config',1,6,'保存科目与满分');node(f,'confirm',0,7,'核对考试配置结果');node(f,'end',2,8,'按确认安排整理考试成绩','end')
path(f,'s','subject','exam','date');edge(f,'date','fix','否','return');edge(f,'fix','exam','修正后重交','return');edge(f,'date','save','是');path(f,'save','full','used');edge(f,'used','resolve','是：先核查');edge(f,'resolve','full','保留或核实后重选','return');edge(f,'used','config','否');path(f,'config','confirm','end')

f=flow(s,'class-disable','停用班级前如何处理在班师生','教学班撤并、结束使用，准备停用班级',['教务管理员','系统','相关教师'],['拟停用班级','当前在班学生名单','当前任教安排'],['可停用的班级','保留的班级历史资料'],['这是业务上的停止使用；当前没有物理删除班级及历史成绩的操作。'])
node(f,'s',0,0,'确认班级结束使用','start');node(f,'submit',0,1,'选择班级并提交停用',module='师生班级与考试');node(f,'used',1,1,'仍有在籍学生或有效任教？','decision')
node(f,'list',1,2,'告知仍需处理的师生关联',outputs=['停用受阻提示'])
node(f,'arrange',2,3,'确认学生去向和任教结束安排',mode='manual');node(f,'move',0,3,'先调整学生和任教关系','subprocess',target='student-change',detail='在学生页调整班级或状态，在教师任教页调整或停用相应关系。')
node(f,'retry',0,4,'再次提交班级停用');node(f,'save',1,5,'停用班级并保留历史');node(f,'end',0,6,'核对停用结果','end')
path(f,'s','submit','used');edge(f,'used','list','是');path(f,'list','arrange','move','retry');edge(f,'retry','used','重新检查','return');edge(f,'used','save','否');path(f,'save','end')
s['notes']=[['外部资料怎么改','由成绩文件或旧资料来源管理的档案，先回原来源更正，再按对应接收流程更新；不能假定所有档案都可在页面直接编辑。'],['删除与停用的业务区别','停用是结束后续使用并保留历史；新建、转班、任教调整都不会自动删除原有成绩、报告和会话。']]
