s=section('scores','成绩导入','从成绩负责人准备资料，到学校核对、系统检查、确认导入和更正错误。','让每一份成绩在被师生使用前，都能说明是谁提供、怎样检查、错误如何退回。')
f=flow(s,'upload-check','准备成绩 → 上传 → 预检 → 退回修正','考试结束，成绩负责人完成本次成绩整理',['成绩负责人','教务管理员','系统'],['学校信息表','班级名单','学生名单','考试信息表','学科清单','考试总分表','学科成绩表','小题得分表'],['通过检查的待导入批次','或可逐项处理的问题清单'],['当前使用八类固定名称的CSV文件；无内容的文件可保留表头。具体文件名见“业务资料与问答用途”。','修正文件内容后使用新批次编号上传；如果只是列对应错误，可在当前批次修正对应关系后重新预检。'])
node(f,'s',0,0,'考试成绩整理完成','start');node(f,'prepare',0,1,'整理名单、考试信息和三类成绩',mode='manual',inputs=f['inputs'],outputs=['待提交成绩文件'])
node(f,'hand',0,2,'核对资料后交给导入人员',mode='manual',detail='这是学校内部资料交接；系统不自动生成或从阅卷系统实时拉取这些文件。')
node(f,'upload',1,2,'填写批次编号并上传文件',module='成绩导入')
node(f,'file',2,3,'文件可以读取？','decision',rule='文件名称、编码、表头和行列结构符合要求；整批不超过5MB、5000行。')
node(f,'badfile',0,4,'修复文件格式后重新提交',mode='manual');node(f,'map',1,4,'确认各列代表哪项业务信息',inputs=['上传文件的列名','目标资料项'],detail='例如把“考号”对应到学校确定的学生标识；同名列可自动对应，也可复用映射模板。')
node(f,'preview',1,5,'发起预检');node(f,'valid',2,5,'学生、考试、分数均匹配？','decision',rule='校验本校范围、学生和考试对应关系、重复数据、数值、得分不超满分、丢分正确及同科满分一致。')
node(f,'issues',2,6,'列出错误位置与原因',outputs=['文件名','所在行','错误项','修正提示'])
node(f,'classify',1,6,'问题出在列对应还是内容？','decision')
node(f,'revise',0,7,'核对原成绩并修正内容',mode='manual',inputs=['错误清单','原始成绩资料'])
node(f,'ready',1,8,'核对无误，准备确认导入','end',outputs=['检查通过的导入批次'],target='commit-import')
path(f,'s','prepare','hand','upload','file');edge(f,'file','badfile','否','return');edge(f,'badfile','upload','重新上传','return');edge(f,'file','map','是');path(f,'map','preview','valid');edge(f,'valid','ready','全部通过');edge(f,'valid','issues','存在错误','return');path(f,'issues','classify');edge(f,'classify','map','列对应错误','return');edge(f,'classify','revise','资料内容错误','return');edge(f,'revise','upload','新批次重新上传','return')

f=flow(s,'commit-import','确认导入 → 查看结果 → 开始使用','导入批次已通过预检，导入人员决定正式保存',['教务管理员','系统','教师 / 学生'],['检查通过的成绩批次','核对后的资料项对应关系'],['正式保存的考试成绩','成功数量或失败说明','待绑定账号数量'],['上传和预检都不等于成绩已可用；导入成功后师生再主动刷新或查询。','成功批次不能在当前功能中直接撤销；需要更正时走新的更正批次。'])
node(f,'s',0,0,'预检通过且已核对内容','start');node(f,'confirm',0,1,'点击确认导入',module='成绩导入');node(f,'freeze',1,1,'锁定本次内容并开始处理')
node(f,'valid',1,2,'正式保存前复核通过？','decision');node(f,'back',0,3,'查看变化并重新预检','subprocess',target='upload-check',detail='若在预检后身份、考试或题目来源发生变化，需要重新检查，不能强行保存。')
node(f,'save',1,4,'成批保存名单、考试与成绩');node(f,'success',1,5,'本批是否全部保存成功？','decision')
node(f,'failed',1,6,'提示失败，撤回本批未完成写入',detail='整批失败不会留下这次写到一半的业务结果。')
node(f,'retry',0,6,'核对失败原因后重试',detail='检查仍有效的批次可以重试；检查已失效时先重新预检。',mode='manual')
node(f,'receipt',0,7,'查看数量、结果与未绑定账号',inputs=['导入回执','成功记录数量','未绑定账号数量'])
node(f,'accounts',0,8,'需要时补做学生账号绑定','subprocess',target='student-onboard',detail='未绑定账号数量指本校当前未绑定档案；已有绑定学生不需重复操作。')
node(f,'read',2,8,'查询本次学情或发起成绩问答',module='班级分析 / 学生学情 / 智能问答');node(f,'end',2,9,'本次成绩可用于教学与答疑','end')
path(f,'s','confirm','freeze','valid');edge(f,'valid','back','否','return');edge(f,'back','confirm','复核通过再确认','return');edge(f,'valid','save','是');path(f,'save','success');edge(f,'success','failed','否','return');path(f,'failed','retry');edge(f,'retry','valid','修复后再处理','return');edge(f,'success','receipt','是');edge(f,'receipt','accounts','有未绑定学生时','optional');path(f,'accounts','read');edge(f,'receipt','read','已具备访问条件');path(f,'read','end')

f=flow(s,'score-correction','发现分数错误后如何更正','老师或学生发现成绩与学校原始资料不一致',['教师 / 学生','成绩负责人','教务管理员','系统'],['具体学生、考试、学科与题号','疑似错误的分数','学校原始成绩材料'],['已核实的正确成绩','更正导入结果','向提出问题的人反馈的处理说明'],['反馈本身不会改分；必须由资料负责人核实后，走新的成绩导入流程。','更正成功后，新查询使用新成绩；已保存的旧回答仍保留当时依据，学生需要重新提问。'])
node(f,'s',0,0,'发现分数疑似错误','start');node(f,'submit',0,1,'说明错误位置并提供核对材料',detail='可提交反馈或联系学校。提出质疑不直接改动成绩。',mode='manual')
node(f,'verify',1,2,'与学校原成绩核对',mode='manual',inputs=['原始成绩资料','具体问题'])
node(f,'wrong',1,3,'确认资料有误？','decision',mode='manual');node(f,'explain',1,4,'说明核对依据与原分数原因',mode='manual')
node(f,'correct',1,5,'修正原成绩并提供更正文件',mode='manual');node(f,'import',2,5,'用新批次预检并确认导入','subprocess',module='成绩导入',target='upload-check')
node(f,'save',3,6,'保存更正结果，供后续查询')
node(f,'reply',1,7,'反馈处理结论和核对方式',mode='manual',detail='如来源为人工工单，可在工单内回复；普通资料交接由学校按原沟通方式完成。')
node(f,'review',0,7,'重新查询成绩或再次提问');node(f,'end',0,8,'核对本次处理结果','end')
path(f,'s','submit','verify','wrong');edge(f,'wrong','explain','否');edge(f,'wrong','correct','是');path(f,'correct','import','save','reply');path(f,'explain','reply','review','end')
s['notes']=[['哪些资料支撑哪类问答','总分和名次用于考试概况；学科成绩用于各科、对比和趋势；小题得分用于失分位置；正式学习诊断另依赖已授权报告。'],['修改和删除如何处理','确认前可以调整列对应；原文件内容变化要新批次。正式成绩更正通过新批次更新；当前没有单条成绩删除或整批撤销按钮。']]
